### PR TITLE
Shop balancing and escape key to exit task

### PR DESCRIPTION
**Pull request by CullanAriyawanse**
I was going to make more changes in other places, but decided I didn't need to, hence the terrible branch name :/

 Changes:
- All upgrades are now functional 
- Added more tiers to certain upgrades
- Adjusted costs for upgrades 
- Adjusted titles and descriptions to certain upgrades 
- Now uses escape key to exit task focus state (was previously backspace)

To change the escape key from stopping the game in unreal (I made it Caps Lock for example):
image

Would really appreciate it if you actually play-tested this branch for two reasons:
1. Check if you like the new upgrade costs (prices too high/low? price scaling too high/not enough?). You can also use this as an opportunity to do a final check of the game and see if you are satisfied with the current state of the game.
2. Make sure that the escape key works for both opening pause screen and exiting task (regardless if it's active or not)

### CODE REVIEW

**Review by Jer-Tran — DISMISSED** [review]
good

**Review by fz8662 — DISMISSED** [review]
ok

**Review by Jer-Tran — APPROVED** [review]
good stuff

**Review by jordanliang5 — APPROVED** [review]
is good

**Pull request merged**
