### PR TITLE
Control room screen

### PR DESCRIPTION
**Pull request by CullanAriyawanse**
image
image
image

If there are any quick changes yall want me to do lmk.

### CODE REVIEW

**Comment by MasterOfCubesAU** [comment]
## Things to do:
- Make the money value to show a float
- Make the integrity value a float
- Change word "durability" to integrity

**Review by fz8662 — DISMISSED** [review]
okay~

**Review by MasterOfCubesAU — DISMISSED** [review]

**Review by jordanliang5 — DISMISSED** [review]

**Comment by Jer-Tran** [comment]
Is it best this session or best overall? Not worth cancelling the PR over dw.
There's gameplay reasons for both, but mainly just want clarity

**Review by Jer-Tran — DISMISSED** [review]
yep, good

**Comment by MasterOfCubesAU** [comment]
> ## Things to do:
> * Make the money value to show a float
> * Make the integrity value a float
> * Change word "durability" to integrity

Resolved

**Review by MasterOfCubesAU — APPROVED** [review]

**Review by Jer-Tran — APPROVED** [review]
yep, better

**Pull request merged**
