### PR TITLE
Calibration task

### PR DESCRIPTION
**Pull request by Jer-Tran**
Addition of calibration task, but still not in main.umap yet

When moving into main level
- Copy + paste it from oxygen_task level
- Delete the props that are in its place, it should be clear which to delete
- Also, new oxygen position is here, incase also bringing that to main later

The location is the area above the staircase, the empty space there, and wires will coincidentally run through it so it fits in better

If you want to test the PA for calibration, best to temp copy + paste it into main, rather than bringing it into my test level, crashed unreal when I did that

### CODE REVIEW

**Review by jordanliang5 — APPROVED** [review]
niceu

**Comment by MasterOfCubesAU** [comment]
Probably crashed because the level is meant to have a PA system blueprint in order for the PA system to work

**Comment by Jer-Tran** [comment]
True, and works fine in main

**Review by fz8662 — APPROVED** [review]
oki

**Pull request merged**
