### PR TITLE
Oxygen task and logic of Task Control

### PR DESCRIPTION
**Pull request by Jer-Tran**
Merging in changes from task_control and oxygen_task

Implement of TaskManager class with logic over timers, task states, selection of task activation, and damage calculation
Oxygen task finished and functional. Desired location is in the oxygen_task level, just copy + paste and do the following changes:

Heads up: TaskManager is incomplete, but the logic is done
Still have not implemented any interaction with the global settings and stuff, namely health, or the activation of task classes which don't exist on my branch yet, or the re-routing of task activation if already active
These are still TODO

I've placed a backup version of TaskManager in a nested folder in the so you all can access it, observe it, etc

### CODE REVIEW

**Review by jordanliang5 — APPROVED** [review]
very cool

**Review by CullanAriyawanse — CHANGES_REQUESTED** [review]
Oxygen task and task control rly fkin good 👍 .
Just two small questions:
1. Did you put this box here and if so are you planning on keeping it?
image

2. Did you lower the height of the bottom floor ceiling such that you can't enter it using the staircase and if so is that intentional?
image

**Comment by Jer-Tran** [comment]
1. The box is BP_TaskExample, it should be removed whenever we get around to actually putting all the stuff in master
2. I think that's an issue on my level only, maybe I pulled before this issue was fixed

**Comment by CullanAriyawanse** [comment]
Is it possible to remove the BP_TaskExample box in your oxygen level now?

**Comment by Jer-Tran** [comment]
What for? We aren't using the levels as levels, what matters is that we can place the oxygen task and manager into the main level when we clean everything up
I noticed all the stuff that you brought up are in the oxygen_task level, which shouldn't affect anything in Main

**Comment by CullanAriyawanse** [comment]
Ohhhh ok I misunderstood how we are merging levels together mbmb. Ok then we are very gud :).

**Review by CullanAriyawanse — APPROVED** [review]

**Pull request merged**
