### PR TITLE
Task control

### PR DESCRIPTION
**Pull request by Jer-Tran**
Cleanup of manager and prep commands for demo
Also bringing in of assets from detailing of engine, upper stair, power, and command rooms

Keep in mind, TaskManager and CommandButton will need to be recompiled with C++ when used in editor

See the script for the order, but debug buttons are
1 -> Pressure
2 -> Oxygen
3 -> Computer
4 -> Electrical
5 -> Engine

0 -> Dive start

### CODE REVIEW

**Review by fz8662 — DISMISSED** [review]
:) gooooood

**Comment by MasterOfCubesAU** [comment]
Are there meant to be input exec pins for the "Dive started" print?
image

**Review by jordanliang5 — DISMISSED** [review]

**Review by fz8662 — DISMISSED** [review]
gooood

**Review by jordanliang5 — APPROVED** [review]

**Comment by MasterOfCubesAU** [comment]
> Are there meant to be input exec pins for the "Dive started" print?
> 
> image
> 
> 

Bump

**Review by CullanAriyawanse — DISMISSED** [review]

**Review by jordanliang5 — CHANGES_REQUESTED** [review]
broken tasks

**Review by MasterOfCubesAU — DISMISSED** [review]

**Review by CullanAriyawanse — DISMISSED** [review]

**Review by jordanliang5 — APPROVED** [review]

**Review by MasterOfCubesAU — APPROVED** [review]

**Pull request merged**
