### PR TITLE
Item physics

### PR DESCRIPTION
**Pull request by Jer-Tran**
Physics generisiced for items now, except for the part where it isn't

For all items, the static mesh that is the item must be re-configured to be a child component of Physics root
For items that have collision problems when held, code must be copied from itemTemplate, and extended to include the static meshes that are of the item. Cannot be genericised due to the fact that the template knows nothing about its children.

Edit: Also supposedly fixed the clickable issue

### CODE REVIEW

**Comment by Jer-Tran** [comment]
#80

**Comment by Jer-Tran** [comment]
Also included here is a fix for the weird ass click detection

**Review by fz8662 — APPROVED** [review]
oki

**Review by jordanliang5 — APPROVED** [review]
amazing work as always

**Pull request merged**
