### PR TITLE
Power up

### PR DESCRIPTION
**Pull request by fz8662**
power updrage

### CODE REVIEW

**Review by Jer-Tran — DISMISSED** [review]
good

**Comment by CullanAriyawanse** [comment]
Hey Joe I have some problems with the current PR:
1. I don't know if this was a problem before but there are some times when I can't click the wire. I think this happens in situations when the error message is stuck on the screen 
2. I think we need to change the style of the error message to be different to 3d text (maybe something like regular text on the screen, similar to the press e to interact text). I think we can discuss ideas for the styling tomorrow during tomorrow's tutorial.

**Review by CullanAriyawanse — CHANGES_REQUESTED** [review]
Request in comments

**Review by jordanliang5 — CHANGES_REQUESTED** [review]
buggy

**Review by CullanAriyawanse — APPROVED** [review]

**Review by jordanliang5 — APPROVED** [review]
nice

**Pull request merged**
